package com.jonashao.musicrecommender.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "RECORDER".
 */
public class Recorder {

    private Long id;
    private Integer ActionCode;
    private java.util.Date ActionDate;
    private long MusicID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Recorder() {
    }

    public Recorder(Long id) {
        this.id = id;
    }

    public Recorder(Long id, Integer ActionCode, java.util.Date ActionDate, long MusicID) {
        this.id = id;
        this.ActionCode = ActionCode;
        this.ActionDate = ActionDate;
        this.MusicID = MusicID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getActionCode() {
        return ActionCode;
    }

    public void setActionCode(Integer ActionCode) {
        this.ActionCode = ActionCode;
    }

    public java.util.Date getActionDate() {
        return ActionDate;
    }

    public void setActionDate(java.util.Date ActionDate) {
        this.ActionDate = ActionDate;
    }

    public long getMusicID() {
        return MusicID;
    }

    public void setMusicID(long MusicID) {
        this.MusicID = MusicID;
    }

    // KEEP METHODS - put your custom methods here
    private static boolean[] playHistory = new boolean[1024];

    public synchronized void writeHistory() {
        playHistory[(int) MusicID & (0x3ff)] = true;
    }

    /**
     * @return if music with selected id was played lately, return true
     */
    public static synchronized boolean wasPlayed(long musicID) {
        return playHistory[(int) musicID & (0x3ff)];
    }
    // KEEP METHODS END

}
