package com.jonashao.musicrecommender.models;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SUBJECTION".
 */
public class Subjection {

    private Long id;
    private Float DegreeOfMembership;
    private long musicID;
    private long clusterID;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Subjection() {
    }

    public Subjection(Long id) {
        this.id = id;
    }

    public Subjection(Long id, Float DegreeOfMembership, long musicID, long clusterID) {
        this.id = id;
        this.DegreeOfMembership = DegreeOfMembership;
        this.musicID = musicID;
        this.clusterID = clusterID;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Float getDegreeOfMembership() {
        return DegreeOfMembership;
    }

    public void setDegreeOfMembership(Float DegreeOfMembership) {
        this.DegreeOfMembership = DegreeOfMembership;
    }

    public long getMusicID() {
        return musicID;
    }

    public void setMusicID(long musicID) {
        this.musicID = musicID;
    }

    public long getClusterID() {
        return clusterID;
    }

    public void setClusterID(long clusterID) {
        this.clusterID = clusterID;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
